# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: inokomi
description: my portfolio !!
baseurl: "" # the subpath of your site, e.g. /support
url: https://inokomi.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: inokomi #Define whether this is a knowledge base, help center, or something else
use_authors: false #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: "@inokomi"
header: hi, i'm kath
subheader: Always eager to learn and explore new technologies!

meta_image: odin-meta.png

# Social Links
twitter_username: inokomi
facebook_page:
github_username: inokomi
email: ino2komi@gmail.com
linkedin_page:
instagram_username: 


# Navivation
nav_item_one: Github
nav_item_one_link: https://inokomi.github.io

nav_item_two: Twitter
nav_item_two_link: https://twitter.com/inokomi

nav_item_three: #
nav_item_three_link: #

nav_button: Home
nav_button_link: https://inokomi.github.io

# More Help
help_one_title: Contact Me
help_one_content: Feel free to reach out through email, phone, or through social media. I look forward to hearing from you! valeriok2001@gmail.com +639992218606
help_one_button: LinkedIn
help_one_link: https://www.linkedin.com/in/katherine-valerio-2514241a2/

help_two_title: Placeholder
help_two_content: Hmm.. What can I put here?
help_two_button: Link
help_two_link: #

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
