
title: inokomi
description: my portfolio !!
baseurl: "" # the subpath of your site, e.g. /support
url: https://inokomi.github.io 
permalink: /:categories/:title

content_type: inokomi 
use_authors: false

brand_logo: logo.png
brand_name: "@inokomi"
header: Hi, I'm Kath
subheader: Always eager to learn and explore new technologies!

meta_image: meta.png

# Social Links
twitter_username: 
facebook_page:
github_username: inokomi
email: ino2komi@gmail.com
linkedin_page:
instagram_username: 


# Nav
nav_item_one: Github
nav_item_one_link: https://github.com/inokomi

nav_item_two: 
nav_item_two_link: 

nav_item_three: #
nav_item_three_link: #

nav_button: Home
nav_button_link: https://inokomi.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
